// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

import { Address, DataSourceTemplate } from "@graphprotocol/graph-ts";

export class Pair extends DataSourceTemplate {
  static create(address: Address): void {
    DataSourceTemplate.create("Pair", [address.toHex()]);
  }
}

export class ZirconPylon extends DataSourceTemplate {
  static create(address: Address): void {
    DataSourceTemplate.create("ZirconPylon", [address.toHex()]);
  }
}

export class ZirconPoolToken extends DataSourceTemplate {
  static create(address: Address): void {
    DataSourceTemplate.create("ZirconPoolToken", [address.toHex()]);
  }
}
